server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.10.9:3306/login_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # 首次自动建表；生产建议改为 none + 迁移脚本
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: never
